server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - 'health'
          - 'loggers'
          - 'hystrix.stream'
          - 'beans'
          - 'conditions'
          - 'heapdump'
          - 'threaddump'
          - 'metrics'
          - 'mappings'
          - 'channels'
logging:
  group:
    aeo: com.aeo.checkout
spring:
  banner:
    location: static/banner.txt
  application:
    name: checkout-fraud-check
  sleuth:
    hystrix:
      strategy:
        enabled: true
---
hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 1000
  command.aciCall.circuitBreaker.enabled: true
  command.aciCall.fallback.enabled: true
  command.aciCall.execution.timeout.enabled: true
  command.aciCall.requestCache.enabled: false
  command.aciCall.requestLog.enabled: false
  command.aciCall.circuitBreaker.requestVolumeThreshold: 1
  command.aciCall.circuitBreaker.errorThresholdPercentage: 3
  command.aciCall.circuitBreaker.sleepWindowInMilliseconds: 60000
  command.aciCall.execution.isolation.thread.timeoutInMilliseconds: 15000
  command.aciCall.metrics.rollingStats.timeInMilliseconds: 60000
  command.aciCall.metrics.rollingStats.numBuckets: 60
  command.aciCall.metrics.healthSnapshot.intervalInMilliseconds: 60000
aci-client:
  division-number: "ae_ugp_rs"
  client-id: "000450030001"
  ssl-key-id: "20171"
  config-path: "src/main/resources/data/security"
fraud:
  enabled: true
aeo-logging:
  exclude-routes:
  - '/actuator'
  - '/favicon'
