server:
  port: 8080
management:
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 
          - 'health'
          - 'loggers'
          - 'hystrix.stream'
          - 'beans'
          - 'conditions'
          - 'heapdump'
          - 'threaddump'
          - 'metrics'
          - 'mappings'
          - 'channels'
spring:
  banner:
    location: classpath:static/banner.txt
  application:
    name: checkout-submit-order
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  sleuth:
    hystrix:
      strategy:
        enabled: true
  cloud:
    gcp:
      core:
        enabled: false
      pubsub:
        enabled: false
app-configs:
  split-call-enabled: false
  split-call-endpoint: "localhost/order/v1/split/%s"
  submit-order-project-id: "checkout-submit-order-project-id"
  submit-order-subscription: "checkout-submit-order-sub-local"
  fulfill-order-project-id: "post-checkout-pubsub-project-id"
  fulfill-order-topic-name: "fulfillment-intake-topic-local"
  basic-auth-key: "basicAuthKey"
aeo-logging:
  exclude-routes:
  - '/actuator'
  - '/favicon'
  - 'swagger'
logging:
  group:
    aeo: com.aeo.checkout
hystrix:
  metrics:
    enabled: true
    polling-interval-ms: 1000
  threadpool.checkout.allowMaximumSizeToDivergeFromCoreSize: true
  threadpool.checkout.coreSize: 25
  threadpool.checkout.maximumSize: 100
  threadpool.checkout.maxQueueSize: 100
  threadpool.checkout.queueSizeRejectionThreshold: 100
  threadpool.checkout.keepAliveTimeMinutes: 1
  command.apisgCall.circuitBreaker.enabled: true
  command.apisgCall.fallback.enabled: true
  command.apisgCall.execution.timeout.enabled: true
  command.apisgCall.requestCache.enabled: false
  command.apisgCall.requestLog.enabled: false
  command.apisgCall.circuitBreaker.requestVolumeThreshold: 5
  command.apisgCall.circuitBreaker.errorThresholdPercentage: 5
  command.apisgCall.circuitBreaker.sleepWindowInMilliseconds: 60000
  command.apisgCall.execution.isolation.strategy: THREAD
  command.apisgCall.execution.isolation.thread.timeoutInMilliseconds: 30000
  command.apisgCall.metrics.rollingStats.timeInMilliseconds: 60000
  command.apisgCall.metrics.rollingStats.numBuckets: 60
  command.apisgCall.metrics.healthSnapshot.intervalInMilliseconds: 60000
