
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'
    spec:
      containers:
      - image: gcr.io/aeo-gke-terraform-f793/rabbitmq:3.8-management-alpine
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        name: {{ .Release.Name }}
        ports:
        - containerPort: 15672
        - containerPort: 5672
        env:
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: rabbitmq-password
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: rabbitmq-username
        resources:
          requests:
            memory: "256Mi"
            cpu: 200m
          limits:
            memory: "1024Mi"
