apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - port: 15672
    name: http-managememt
    protocol: TCP
    targetPort: 15672
  - port: 5672
    name: http-client
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
