## https://codecentric.github.io/chaos-monkey-spring-boot/2.3.0/#_http_endpoint
management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - 'health'
        - 'info'
        - 'metrics'
        - 'chaosmonkey'
## https://codecentric.github.io/chaos-monkey-spring-boot/2.3.0/#_properties
chaos:
  monkey:
    enabled: true
    watcher:
      component: true
      controller: true
      repository: false
      rest-controller: true
      service: true
    assaults:
      level: 2
      latency-active: true
      latency-range-start: 3000
      latency-range-end: 5000
      exceptions-active: true
      exception:
        type: 'java.lang.RuntimeException'
        arguments:
        - class-name: 'java.lang.String'
          value: 'Chaos'
      memory-active: true
      memory-milliseconds-hold-filled-memory: 30000
      memory-milliseconds-wait-next-increase: 100
      memory-fill-target-fraction: 0.90
      memory-fill-increment-fraction: 0.60
      kill-application-active: true
      watched-custom-services:
        - ''
## To Start
# local:
# ./gradlew bootRun --args='--spring.profiles.active=chaos-monkey'
# 
# cloud enable:
# cf set-env ${bamboo.app_name} SPRING_PROFILES_ACTIVE chaos-monkey
# cf restage ${bamboo.app_name}
#
# cloud disable:
# cf unset-env SPRING_PROFILES_ACTIVE
# cf restage ${bamboo.app_name}
##