spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbit}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBITMQ_HOST:rabbit}
                port: 5672
                username: ${RABBITMQ_USER:guest}
                password: ${RABBITMQ_PASS:guest}
    gcp:
      core:
        enabled: true
      pubsub:
        enabled: true
        project-id: ${SAME_DAY_DELIVERY_PUBSUB_PROJECT_ID}
        subscriber:
          executor-threads: 4
      subscription: ${SAME_DAY_DELIVERY_PUBSUB_SUBSCRIPTION}
sdd:
  service:
    patchurl: ${SAME_DAY_DELIVERY_API_URL}
    auth: ${SAME_DAY_DELIVERY_API_AUTHORIZATION}
