spring:
  cloud:
    gcp:
      credentials:
        encoded-key: ${vcap.services.same-day-delivery-pubsub-service.credentials.private_key}
      core:
        enabled: true
      pubsub:
        enabled:  true
        subscriber:
          executor-threads: 4
        credentials:
          encoded-key: ${vcap.services.same-day-delivery-pubsub-service.credentials.private_key}
      subscription: ${vcap.services.same-day-delivery-pubsub-service.credentials.subscription_name:same-day-delivery-subscription-dev}
sdd:
  service:
    patchurl: ${vcap.services.same-day-delivery-service.credentials.api_url:https://samedaysession.stg.shoprunner.io/retailers/AEGL/checkouts/}
    auth: ${vcap.services.same-day-delivery-service.credentials.api_authorization:Basic YWVnbDJAc2hvcHJ1bm5lci5jb20uc3JzdGc6TFNCWjZQT0Fla29s}