server:
  port: 8084
management:
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 
          - 'health'
          - 'loggers'
          - 'beans'
          - 'conditions'
          - 'heapdump'
          - 'threaddump'
          - 'metrics'
          - 'mappings'
          - 'channels'
logging:
  group:
    aeo: com.aeo.checkout.sdd
      
spring:
  application:
    name: checkout-same-day-delivery
  cloud:
    stream:
      bindings:
        sddFailedPatchOrdersReprocessor:
          binder: rabbit
          destination: sdd-failed
          group: request-queue
          producer:
            required-groups: request-queue
        sddFailedPatchOrdersRetry:
          binder: rabbit
          destination: sdd-failed-retry
          group: request-queue
          consumer:  
            default-retryable: true
            max-attempts: 3
            back-off-multiplier: 1.5
            back-off-initial-interval: 60000
            back-off-max-interval: 180000
      rabbit:
        bindings:
          sddFailedPatchOrdersReprocessor:
            producer:
              auto-bind-dlq: true
              ttl: 18
              dead-letter-exchange: sdd-failed-retry
              dead-letter-exchange-type: topic
              dead-letter-queue-name: sdd-failed-retry.request-queue
              dead-letter-routing-key: sdd-failed.request-queue
              dlq-dead-letter-exchange: sdd-failed-retry-dlq
              dlq-dead-letter-routing-key: sdd-failed-retry.request-queue
          sddFailedPatchOrdersRetry:
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange: sdd-failed-retry-dlq
              dead-letter-queue-name: sdd-failed-retry-dlq.failed-queue
              dead-letter-routing-key: sdd-failed-retry.request-queue
    gcp:
      core:
        enabled: false
      pubsub:
        enabled: false              
      subscription: same-day-delivery-subscription-dev
aeo-logging:
  exclude-routes:
  - '/actuator'
  - '/favicon'
sdd:
  service:
    patchurl: 'https://samedaysession.stg.shoprunner.io/retailers/AEGL/checkouts/'
    auth: 'Basic YWVnbDJAc2hvcHJ1bm5lci5jb20uc3JzdGc6TFNCWjZQT0Fla29s'
