apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Chart.Name }}-http
      port: {{ include "service-port" . }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
