
package aeo.integration.vertex.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculateTaxWSService90", targetNamespace = "http://www.vertexinc.com/oseries/services/CalculateTax90", wsdlLocation = "https://dev-tax.ae.com/vertex-ws/services/CalculateTax90?wsdl")
public class CalculateTaxWSService90
    extends Service
{

    private final static URL CALCULATETAXWSSERVICE90_WSDL_LOCATION;
    private final static WebServiceException CALCULATETAXWSSERVICE90_EXCEPTION;
    private final static QName CALCULATETAXWSSERVICE90_QNAME = new QName("http://www.vertexinc.com/oseries/services/CalculateTax90", "CalculateTaxWSService90");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://dev-tax.ae.com/vertex-ws/services/CalculateTax90?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATETAXWSSERVICE90_WSDL_LOCATION = url;
        CALCULATETAXWSSERVICE90_EXCEPTION = e;
    }

    public CalculateTaxWSService90() {
        super(__getWsdlLocation(), CALCULATETAXWSSERVICE90_QNAME);
    }

    public CalculateTaxWSService90(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATETAXWSSERVICE90_QNAME, features);
    }

    public CalculateTaxWSService90(URL wsdlLocation) {
        super(wsdlLocation, CALCULATETAXWSSERVICE90_QNAME);
    }

    public CalculateTaxWSService90(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATETAXWSSERVICE90_QNAME, features);
    }

    public CalculateTaxWSService90(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateTaxWSService90(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculateTaxWS90
     */
    @WebEndpoint(name = "CalculateTax90")
    public CalculateTaxWS90 getCalculateTax90() {
        return super.getPort(new QName("http://www.vertexinc.com/oseries/services/CalculateTax90", "CalculateTax90"), CalculateTaxWS90.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculateTaxWS90
     */
    @WebEndpoint(name = "CalculateTax90")
    public CalculateTaxWS90 getCalculateTax90(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.vertexinc.com/oseries/services/CalculateTax90", "CalculateTax90"), CalculateTaxWS90.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATETAXWSSERVICE90_EXCEPTION!= null) {
            throw CALCULATETAXWSSERVICE90_EXCEPTION;
        }
        return CALCULATETAXWSSERVICE90_WSDL_LOCATION;
    }

}
