
package aeo.integration.vertex.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculateTaxWS90", targetNamespace = "http://www.vertexinc.com/oseries/services/CalculateTax90")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculateTaxWS90 {


    /**
     * 
     * @param part
     * @return
     *     returns aeo.integration.vertex.client.VertexEnvelope
     */
    @WebMethod
    @WebResult(name = "VertexEnvelope", targetNamespace = "urn:vertexinc:o-series:tps:9:0", partName = "VertexEnvelope")
    public VertexEnvelope calculateTax90(
        @WebParam(name = "VertexEnvelope", targetNamespace = "urn:vertexinc:o-series:tps:9:0", partName = "part")
        VertexEnvelope part);

}
