envVars:
  ENV: "perf"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  VERTEX_SERVICE_ENDPOINT: "https://stress-tax.ae.com/vertex-ws/services/CalculateTax90"
  VERTEX_WSDL_ENDPOINT: "https://stress-tax.ae.com/vertex-ws/services/CalculateTax90?wsdl"
  VERTEX_USERNAME: "eComm"
  VERTEX_PASSWORD: "vertex"
  NEW_RELIC_APP_NAME: "checkout-tax-calculator-perf"

#Environment name
env: perf

#Deployment values
deployment:
  replicas: 1

#Workload identity enablement for the GCP API access
workloadIdentity:
  enabled: false
  gsa_name:
  gcp_project_id: aeo-gke-internal-nonprod-4379

#Horizontal Pod autoscaling options
autoscaling:
  enabled: true
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

#Ingress values
ingress:
  enabled: true
  domain: int-perf.ae-gcp.io
