envVars:
  ENV: "sit"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  VERTEX_SERVICE_ENDPOINT: "https://dev-tax.ae.com/vertex-ws/services/CalculateTax90"
  VERTEX_WSDL_ENDPOINT: "https://dev-tax.ae.com/vertex-ws/services/CalculateTax90?wsdl"
  VERTEX_USERNAME: "eComm"
  VERTEX_PASSWORD: "vertex"
  NEW_RELIC_APP_NAME: "checkout-tax-calculator-sit"

#Environment name
env: sit

#Deployment values
deployment:
  replicas: 1

#Workload identity enablement for the GCP API access
workloadIdentity:
  enabled: false
  gsa_name: 
  gcp_project_id: aeo-gke-internal-nonprod-4379

#Horizontal Pod autoscaling options
autoscaling:
  enabled: false
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

#Ingress values
ingress:
  enabled: true
  domain: int-np.ae-gcp.io
