apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
         {{- include "selectorLabels" . | nindent 8 }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
      containers:
        {{- if .Values.cloudsqlProxy.enabled }}
        - name: cloud-sql-proxy
          image: gcr.io/aeo-gke-terraform-f793/cloudsql-docker/gce-proxy:1.19.1
          command:
            - "/cloud_sql_proxy"
            - {{ .Values.cloudsqlProxy.instanceConnectionName }}
          securityContext:
            runAsNonRoot: true
        {{- end }}
        - name: {{ .Chart.Name }}
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          image: {{ include "image-fullname" .}}
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "fullname" . }}
          {{- if .Values.envSecrets }}
            - secretRef:
                name: {{ include "fullname" . }}
          {{- end }}
          env:
            - name: ENV
              value: {{ .Values.env }}
            {{ include "get-secrets" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: 20
            timeoutSeconds: 5
          ports:
          - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: 5
      {{- if .Values.workloadIdentity.enabled }}
      serviceAccountName: {{ .Values.workloadIdentity.gsa_name }}
      {{ else }}
      serviceAccountName: {{ include "fullname" . }}
      {{ end }}
      volumes:
      - name: tmp
        emptyDir: {}
