apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.envVars }}
  {{- if $key }}
  {{- if not (hasPrefix "${k8s_secret://" $value) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
