envVars:
  ENV: "perf"
  RABBITMQ_PASS: "${k8s_secret://rabbit/rabbitmq-password}"
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SAME_DAY_DELIVERY_API_URL: "https://samedaysession.stg.shoprunner.io/retailers/AEGL/checkouts/"
  SAME_DAY_DELIVERY_API_AUTHORIZATION: "Basic YWVnbDJAc2hvcHJ1bm5lci5jb20uc3JzdGc6TFNCWjZQT0Fla29s"
  SAME_DAY_DELIVERY_PUBSUB_PROJECT_ID: "aeo-pivotal-production"
  SAME_DAY_DELIVERY_PUBSUB_SUBSCRIPTION: "same-day-delivery-subscription-perf"
  NEW_RELIC_APP_NAME: "checkout-same-day-delivery-perf"

#Environment name
env: perf

#Deployment values
deployment:
  replicas: 1

#Workload identity enablement for the GCP API access
workloadIdentity:
  enabled: true
  gsa_name: customer-checkout-sdd-perf
  gcp_project_id: aeo-gke-internal-nonprod-4379

#Horizontal Pod autoscaling options
autoscaling:
  enabled: true
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

#Ingress values
ingress:
  enabled: true
  domain: int-perf.ae-gcp.io
